server:
  port: 8084
spring:
  application:
    name: shipping-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipping-service-group
      auto-offset-reset: earliest
